// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_contacts_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_contacts_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureContactsFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Open a contacts folder on the real filesystem.
 */
public protocol ContactsSessionProtocol: AnyObject, Sendable {

    /**
     * Assign a tag to several contacts through typed draft saves.
     */
    func assignTag(tag: String, ids: [String]) throws  -> UInt64

    /**
     * `text-row`s for one group's field choices. `id` is `field|source`.
     */
    func conflictChoiceRows(canonicalName: String) throws  -> [TextRow]

    /**
     * Field-level preview for one Syncthing group.
     */
    func conflictPreview(canonicalName: String) throws  -> ConflictPreview

    /**
     * Conflict groups with display copy and a typed merge disposition.
     */
    func conflictRows() throws  -> [ConflictRow]

    /**
     * Reload the authoritative Card by id and return its typed edit draft.
     */
    func contactEditDraft(id: String) throws  -> ContactEditDraft

    /**
     * Delete one card (and its file when it was the last sibling).
     */
    func delete(id: String) throws

    /**
     * Delete several contacts with one logged delete action per id.
     */
    func deleteMany(ids: [String]) throws  -> UInt64

    /**
     * Canonical vCard text for an explicit export operation only.
     */
    func exportVcardText(id: String) throws  -> String

    /**
     * `field-row`s for one card.
     */
    func fieldRows(id: String) throws  -> [FieldRow]

    /**
     * Basename of the `.vcf` this id lives in.
     */
    func fileName(id: String) throws  -> String

    /**
     * Display-ready contact rows for a search query and optional tag filter.
     */
    func filteredListRows(query: String, tag: String?) throws  -> [TextRow]

    /**
     * `text-row` list, sorted by title.
     */
    func listRows() throws  -> [TextRow]

    /**
     * Empty typed draft for creating a contact.
     */
    func newContactDraft()  -> ContactEditDraft

    /**
     * Re-walk the folder.
     */
    func reload() throws

    /**
     * Remove a tag from every contact through typed draft saves.
     */
    func removeTag(tag: String) throws  -> UInt64

    /**
     * Rename a tag on every contact through typed draft saves.
     */
    func renameTag(oldName: String, newName: String) throws  -> UInt64

    /**
     * Apply a merge. `choice_ids` are `field|source` from [`Self::conflict_choice_rows`].
     * Empty is enough for Auto / DeletedVersusModified. Choice without a pick fails.
     */
    func resolveGroup(canonicalName: String, choiceIds: [String]) throws

    /**
     * Validate and save a typed contact edit.
     */
    func saveContact(command: SaveContactCommand) throws  -> ContactEditDraft

    /**
     * Live-search hits with the first matching field.
     */
    func searchHits(query: String, tag: String?) throws  -> [SearchHit]

    /**
     * Display-ready tag filters with contact counts.
     */
    func tagRows() throws  -> [TextRow]

}
/**
 * Open a contacts folder on the real filesystem.
 */
open class ContactsSession: ContactsSessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_contacts_ffi_fn_clone_contactssession(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_contacts_ffi_fn_free_contactssession(handle, $0) }
    }


    /**
     * Walk `root` and load surviving `.vcf` files.
     *
     * `device` is this device's log partition (ADR 0005 R4/R5). The
     * identifier stays off the synced folder.
     */
public static func `open`(root: String, device: String)throws  -> ContactsSession  {
    return try  FfiConverterTypeContactsSession_lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_constructor_contactssession_open(
        FfiConverterString.lower(root),
        FfiConverterString.lower(device),uniffiCallStatus
    )
})
}



    /**
     * Assign a tag to several contacts through typed draft saves.
     */
open func assignTag(tag: String, ids: [String])throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_assign_tag(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(tag),
        FfiConverterSequenceString.lower(ids),uniffiCallStatus
    )
})
}

    /**
     * `text-row`s for one group's field choices. `id` is `field|source`.
     */
open func conflictChoiceRows(canonicalName: String)throws  -> [TextRow]  {
    return try  FfiConverterSequenceTypeTextRow.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_conflict_choice_rows(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(canonicalName),uniffiCallStatus
    )
})
}

    /**
     * Field-level preview for one Syncthing group.
     */
open func conflictPreview(canonicalName: String)throws  -> ConflictPreview  {
    return try  FfiConverterTypeConflictPreview_lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_conflict_preview(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(canonicalName),uniffiCallStatus
    )
})
}

    /**
     * Conflict groups with display copy and a typed merge disposition.
     */
open func conflictRows()throws  -> [ConflictRow]  {
    return try  FfiConverterSequenceTypeConflictRow.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_conflict_rows(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

    /**
     * Reload the authoritative Card by id and return its typed edit draft.
     */
open func contactEditDraft(id: String)throws  -> ContactEditDraft  {
    return try  FfiConverterTypeContactEditDraft_lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_contact_edit_draft(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),uniffiCallStatus
    )
})
}

    /**
     * Delete one card (and its file when it was the last sibling).
     */
open func delete(id: String)throws   {try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_delete(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),uniffiCallStatus
    )
}
}

    /**
     * Delete several contacts with one logged delete action per id.
     */
open func deleteMany(ids: [String])throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_delete_many(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(ids),uniffiCallStatus
    )
})
}

    /**
     * Canonical vCard text for an explicit export operation only.
     */
open func exportVcardText(id: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_export_vcard_text(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),uniffiCallStatus
    )
})
}

    /**
     * `field-row`s for one card.
     */
open func fieldRows(id: String)throws  -> [FieldRow]  {
    return try  FfiConverterSequenceTypeFieldRow.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_field_rows(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),uniffiCallStatus
    )
})
}

    /**
     * Basename of the `.vcf` this id lives in.
     */
open func fileName(id: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_file_name(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),uniffiCallStatus
    )
})
}

    /**
     * Display-ready contact rows for a search query and optional tag filter.
     */
open func filteredListRows(query: String, tag: String?)throws  -> [TextRow]  {
    return try  FfiConverterSequenceTypeTextRow.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_filtered_list_rows(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),
        FfiConverterOptionString.lower(tag),uniffiCallStatus
    )
})
}

    /**
     * `text-row` list, sorted by title.
     */
open func listRows()throws  -> [TextRow]  {
    return try  FfiConverterSequenceTypeTextRow.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_list_rows(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

    /**
     * Empty typed draft for creating a contact.
     */
open func newContactDraft() -> ContactEditDraft  {
    return try!  FfiConverterTypeContactEditDraft_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_new_contact_draft(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

    /**
     * Re-walk the folder.
     */
open func reload()throws   {try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_reload(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}

    /**
     * Remove a tag from every contact through typed draft saves.
     */
open func removeTag(tag: String)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_remove_tag(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(tag),uniffiCallStatus
    )
})
}

    /**
     * Rename a tag on every contact through typed draft saves.
     */
open func renameTag(oldName: String, newName: String)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_rename_tag(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(oldName),
        FfiConverterString.lower(newName),uniffiCallStatus
    )
})
}

    /**
     * Apply a merge. `choice_ids` are `field|source` from [`Self::conflict_choice_rows`].
     * Empty is enough for Auto / DeletedVersusModified. Choice without a pick fails.
     */
open func resolveGroup(canonicalName: String, choiceIds: [String])throws   {try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_resolve_group(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(canonicalName),
        FfiConverterSequenceString.lower(choiceIds),uniffiCallStatus
    )
}
}

    /**
     * Validate and save a typed contact edit.
     */
open func saveContact(command: SaveContactCommand)throws  -> ContactEditDraft  {
    return try  FfiConverterTypeContactEditDraft_lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_save_contact(
            self.uniffiCloneHandle(),
        FfiConverterTypeSaveContactCommand_lower(command),uniffiCallStatus
    )
})
}

    /**
     * Live-search hits with the first matching field.
     */
open func searchHits(query: String, tag: String?)throws  -> [SearchHit]  {
    return try  FfiConverterSequenceTypeSearchHit.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_search_hits(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),
        FfiConverterOptionString.lower(tag),uniffiCallStatus
    )
})
}

    /**
     * Display-ready tag filters with contact counts.
     */
open func tagRows()throws  -> [TextRow]  {
    return try  FfiConverterSequenceTypeTextRow.lift(try rustCallWithError(FfiConverterTypeContactsError_lift) {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_method_contactssession_tag_rows(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeContactsSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ContactsSession

    public static func lift(_ handle: UInt64) throws -> ContactsSession {
        return ContactsSession(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ContactsSession) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ContactsSession {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ContactsSession, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContactsSession_lift(_ handle: UInt64) throws -> ContactsSession {
    return try FfiConverterTypeContactsSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContactsSession_lower(_ value: ContactsSession) -> UInt64 {
    return FfiConverterTypeContactsSession.lower(value)
}




/**
 * R6 role: command DTO.
 *
 * Editable birthday; `year` is absent for `--MM-DD`.
 */
public struct BirthdayDraft: Equatable, Hashable {
    /**
     * Four-digit year, when known.
     */
    public var year: Int32?
    /**
     * Month 1–12.
     */
    public var month: UInt8
    /**
     * Day 1–31.
     */
    public var day: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Four-digit year, when known.
         */year: Int32?,
        /**
         * Month 1–12.
         */month: UInt8,
        /**
         * Day 1–31.
         */day: UInt8) {
        self.year = year
        self.month = month
        self.day = day
    }




}

#if compiler(>=6)
extension BirthdayDraft: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBirthdayDraft: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BirthdayDraft {
        return
            try BirthdayDraft(
                year: FfiConverterOptionInt32.read(from: &buf),
                month: FfiConverterUInt8.read(from: &buf),
                day: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: BirthdayDraft, into buf: inout [UInt8]) {
        FfiConverterOptionInt32.write(value.year, into: &buf)
        FfiConverterUInt8.write(value.month, into: &buf)
        FfiConverterUInt8.write(value.day, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBirthdayDraft_lift(_ buf: RustBuffer) throws -> BirthdayDraft {
    return try FfiConverterTypeBirthdayDraft.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBirthdayDraft_lower(_ value: BirthdayDraft) -> RustBuffer {
    return FfiConverterTypeBirthdayDraft.lower(value)
}


/**
 * R6 role: command DTO.
 *
 * One field that differs across Syncthing copies.
 */
public struct ConflictFieldPreview: Equatable, Hashable {
    /**
     * Stable field key (`tel:cell`, `fn`, …).
     */
    public var field: String
    /**
     * Visible sides the shell offers as a choice.
     */
    public var sides: [ConflictSide]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Stable field key (`tel:cell`, `fn`, …).
         */field: String,
        /**
         * Visible sides the shell offers as a choice.
         */sides: [ConflictSide]) {
        self.field = field
        self.sides = sides
    }




}

#if compiler(>=6)
extension ConflictFieldPreview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConflictFieldPreview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConflictFieldPreview {
        return
            try ConflictFieldPreview(
                field: FfiConverterString.read(from: &buf),
                sides: FfiConverterSequenceTypeConflictSide.read(from: &buf)
        )
    }

    public static func write(_ value: ConflictFieldPreview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.field, into: &buf)
        FfiConverterSequenceTypeConflictSide.write(value.sides, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConflictFieldPreview_lift(_ buf: RustBuffer) throws -> ConflictFieldPreview {
    return try FfiConverterTypeConflictFieldPreview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConflictFieldPreview_lower(_ value: ConflictFieldPreview) -> RustBuffer {
    return FfiConverterTypeConflictFieldPreview.lower(value)
}


/**
 * R6 role: command DTO.
 *
 * Field-level preview for an explicit Syncthing-group review.
 */
public struct ConflictPreview: Equatable, Hashable {
    /**
     * Group id the shell hands back to [`ContactsSession::resolve_group`].
     */
    public var id: String
    /**
     * Surviving file name.
     */
    public var title: String
    /**
     * Auto / choice / deleted-versus-modified.
     */
    public var kind: MergeKind
    /**
     * Copy basenames that will be deleted on confirm.
     */
    public var discarded: [String]
    /**
     * Merged card as the user will see it if they confirm without edits.
     */
    public var mergedFields: [FieldRow]
    /**
     * Fields that differ. Empty when [`MergeKind::Auto`].
     */
    public var fields: [ConflictFieldPreview]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Group id the shell hands back to [`ContactsSession::resolve_group`].
         */id: String,
        /**
         * Surviving file name.
         */title: String,
        /**
         * Auto / choice / deleted-versus-modified.
         */kind: MergeKind,
        /**
         * Copy basenames that will be deleted on confirm.
         */discarded: [String],
        /**
         * Merged card as the user will see it if they confirm without edits.
         */mergedFields: [FieldRow],
        /**
         * Fields that differ. Empty when [`MergeKind::Auto`].
         */fields: [ConflictFieldPreview]) {
        self.id = id
        self.title = title
        self.kind = kind
        self.discarded = discarded
        self.mergedFields = mergedFields
        self.fields = fields
    }




}

#if compiler(>=6)
extension ConflictPreview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConflictPreview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConflictPreview {
        return
            try ConflictPreview(
                id: FfiConverterString.read(from: &buf),
                title: FfiConverterString.read(from: &buf),
                kind: FfiConverterTypeMergeKind.read(from: &buf),
                discarded: FfiConverterSequenceString.read(from: &buf),
                mergedFields: FfiConverterSequenceTypeFieldRow.read(from: &buf),
                fields: FfiConverterSequenceTypeConflictFieldPreview.read(from: &buf)
        )
    }

    public static func write(_ value: ConflictPreview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterTypeMergeKind.write(value.kind, into: &buf)
        FfiConverterSequenceString.write(value.discarded, into: &buf)
        FfiConverterSequenceTypeFieldRow.write(value.mergedFields, into: &buf)
        FfiConverterSequenceTypeConflictFieldPreview.write(value.fields, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConflictPreview_lift(_ buf: RustBuffer) throws -> ConflictPreview {
    return try FfiConverterTypeConflictPreview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConflictPreview_lower(_ value: ConflictPreview) -> RustBuffer {
    return FfiConverterTypeConflictPreview.lower(value)
}


/**
 * Display-ready conflict group plus typed disposition.
 */
public struct ConflictRow: Equatable, Hashable {
    /**
     * Opaque folder-relative key handed back to merge calls.
     */
    public var id: String
    /**
     * Surviving file path relative to the contacts folder.
     */
    public var title: String
    /**
     * Human-readable number of copies.
     */
    public var subtitle: String
    /**
     * Human-readable disposition.
     */
    public var trailing: String
    /**
     * Typed disposition for shell control flow.
     */
    public var disposition: MergeKind

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Opaque folder-relative key handed back to merge calls.
         */id: String,
        /**
         * Surviving file path relative to the contacts folder.
         */title: String,
        /**
         * Human-readable number of copies.
         */subtitle: String,
        /**
         * Human-readable disposition.
         */trailing: String,
        /**
         * Typed disposition for shell control flow.
         */disposition: MergeKind) {
        self.id = id
        self.title = title
        self.subtitle = subtitle
        self.trailing = trailing
        self.disposition = disposition
    }




}

#if compiler(>=6)
extension ConflictRow: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConflictRow: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConflictRow {
        return
            try ConflictRow(
                id: FfiConverterString.read(from: &buf),
                title: FfiConverterString.read(from: &buf),
                subtitle: FfiConverterString.read(from: &buf),
                trailing: FfiConverterString.read(from: &buf),
                disposition: FfiConverterTypeMergeKind.read(from: &buf)
        )
    }

    public static func write(_ value: ConflictRow, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.subtitle, into: &buf)
        FfiConverterString.write(value.trailing, into: &buf)
        FfiConverterTypeMergeKind.write(value.disposition, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConflictRow_lift(_ buf: RustBuffer) throws -> ConflictRow {
    return try FfiConverterTypeConflictRow.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConflictRow_lower(_ value: ConflictRow) -> RustBuffer {
    return FfiConverterTypeConflictRow.lower(value)
}


/**
 * R6 role: command DTO.
 *
 * One side of a conflicting field.
 */
public struct ConflictSide: Equatable, Hashable {
    /**
     * Copy basename or surviving path.
     */
    public var source: String
    /**
     * Formatted field value on that copy.
     */
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Copy basename or surviving path.
         */source: String,
        /**
         * Formatted field value on that copy.
         */value: String) {
        self.source = source
        self.value = value
    }




}

#if compiler(>=6)
extension ConflictSide: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConflictSide: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConflictSide {
        return
            try ConflictSide(
                source: FfiConverterString.read(from: &buf),
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ConflictSide, into buf: inout [UInt8]) {
        FfiConverterString.write(value.source, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConflictSide_lift(_ buf: RustBuffer) throws -> ConflictSide {
    return try FfiConverterTypeConflictSide.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConflictSide_lower(_ value: ConflictSide) -> RustBuffer {
    return FfiConverterTypeConflictSide.lower(value)
}


/**
 * R6 role: command DTO.
 *
 * Full core-owned contact edit form. Storage-only Card fields do not cross.
 */
public struct ContactEditDraft: Equatable, Hashable {
    /**
     * Existing id; absent for a new contact.
     */
    public var id: String?
    /**
     * Deterministic token of the authoritative Card used to open this draft.
     */
    public var contentToken: String?
    /**
     * FN.
     */
    public var fullName: String
    /**
     * N family.
     */
    public var familyName: String
    /**
     * N given.
     */
    public var givenName: String
    /**
     * N middle.
     */
    public var middleName: String
    /**
     * N prefix.
     */
    public var namePrefix: String
    /**
     * N suffix.
     */
    public var nameSuffix: String
    /**
     * ORG.
     */
    public var organization: String
    /**
     * TITLE.
     */
    public var jobTitle: String
    /**
     * NICKNAME.
     */
    public var nickname: String
    /**
     * URL rows.
     */
    public var urls: [LabeledValueDraft]
    /**
     * TEL rows.
     */
    public var phones: [LabeledValueDraft]
    /**
     * EMAIL rows.
     */
    public var emails: [LabeledValueDraft]
    /**
     * ADR rows.
     */
    public var addresses: [LabeledAddressDraft]
    /**
     * BDAY.
     */
    public var birthday: BirthdayDraft?
    /**
     * NOTE.
     */
    public var note: String
    /**
     * CATEGORIES.
     */
    public var categories: [String]
    /**
     * Decoded PHOTO bytes.
     */
    public var photo: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Existing id; absent for a new contact.
         */id: String?,
        /**
         * Deterministic token of the authoritative Card used to open this draft.
         */contentToken: String?,
        /**
         * FN.
         */fullName: String,
        /**
         * N family.
         */familyName: String,
        /**
         * N given.
         */givenName: String,
        /**
         * N middle.
         */middleName: String,
        /**
         * N prefix.
         */namePrefix: String,
        /**
         * N suffix.
         */nameSuffix: String,
        /**
         * ORG.
         */organization: String,
        /**
         * TITLE.
         */jobTitle: String,
        /**
         * NICKNAME.
         */nickname: String,
        /**
         * URL rows.
         */urls: [LabeledValueDraft],
        /**
         * TEL rows.
         */phones: [LabeledValueDraft],
        /**
         * EMAIL rows.
         */emails: [LabeledValueDraft],
        /**
         * ADR rows.
         */addresses: [LabeledAddressDraft],
        /**
         * BDAY.
         */birthday: BirthdayDraft?,
        /**
         * NOTE.
         */note: String,
        /**
         * CATEGORIES.
         */categories: [String],
        /**
         * Decoded PHOTO bytes.
         */photo: Data?) {
        self.id = id
        self.contentToken = contentToken
        self.fullName = fullName
        self.familyName = familyName
        self.givenName = givenName
        self.middleName = middleName
        self.namePrefix = namePrefix
        self.nameSuffix = nameSuffix
        self.organization = organization
        self.jobTitle = jobTitle
        self.nickname = nickname
        self.urls = urls
        self.phones = phones
        self.emails = emails
        self.addresses = addresses
        self.birthday = birthday
        self.note = note
        self.categories = categories
        self.photo = photo
    }




}

#if compiler(>=6)
extension ContactEditDraft: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeContactEditDraft: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ContactEditDraft {
        return
            try ContactEditDraft(
                id: FfiConverterOptionString.read(from: &buf),
                contentToken: FfiConverterOptionString.read(from: &buf),
                fullName: FfiConverterString.read(from: &buf),
                familyName: FfiConverterString.read(from: &buf),
                givenName: FfiConverterString.read(from: &buf),
                middleName: FfiConverterString.read(from: &buf),
                namePrefix: FfiConverterString.read(from: &buf),
                nameSuffix: FfiConverterString.read(from: &buf),
                organization: FfiConverterString.read(from: &buf),
                jobTitle: FfiConverterString.read(from: &buf),
                nickname: FfiConverterString.read(from: &buf),
                urls: FfiConverterSequenceTypeLabeledValueDraft.read(from: &buf),
                phones: FfiConverterSequenceTypeLabeledValueDraft.read(from: &buf),
                emails: FfiConverterSequenceTypeLabeledValueDraft.read(from: &buf),
                addresses: FfiConverterSequenceTypeLabeledAddressDraft.read(from: &buf),
                birthday: FfiConverterOptionTypeBirthdayDraft.read(from: &buf),
                note: FfiConverterString.read(from: &buf),
                categories: FfiConverterSequenceString.read(from: &buf),
                photo: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: ContactEditDraft, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.contentToken, into: &buf)
        FfiConverterString.write(value.fullName, into: &buf)
        FfiConverterString.write(value.familyName, into: &buf)
        FfiConverterString.write(value.givenName, into: &buf)
        FfiConverterString.write(value.middleName, into: &buf)
        FfiConverterString.write(value.namePrefix, into: &buf)
        FfiConverterString.write(value.nameSuffix, into: &buf)
        FfiConverterString.write(value.organization, into: &buf)
        FfiConverterString.write(value.jobTitle, into: &buf)
        FfiConverterString.write(value.nickname, into: &buf)
        FfiConverterSequenceTypeLabeledValueDraft.write(value.urls, into: &buf)
        FfiConverterSequenceTypeLabeledValueDraft.write(value.phones, into: &buf)
        FfiConverterSequenceTypeLabeledValueDraft.write(value.emails, into: &buf)
        FfiConverterSequenceTypeLabeledAddressDraft.write(value.addresses, into: &buf)
        FfiConverterOptionTypeBirthdayDraft.write(value.birthday, into: &buf)
        FfiConverterString.write(value.note, into: &buf)
        FfiConverterSequenceString.write(value.categories, into: &buf)
        FfiConverterOptionData.write(value.photo, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContactEditDraft_lift(_ buf: RustBuffer) throws -> ContactEditDraft {
    return try FfiConverterTypeContactEditDraft.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContactEditDraft_lower(_ value: ContactEditDraft) -> RustBuffer {
    return FfiConverterTypeContactEditDraft.lower(value)
}


/**
 * `field-row` (ADR 0004 R4).
 */
public struct FieldRow: Equatable, Hashable {
    /**
     * Optional row key.
     */
    public var id: String?
    /**
     * Field name, already chosen.
     */
    public var label: String
    /**
     * Field value, already formatted.
     */
    public var value: String
    /**
     * Whether the shell may edit this row.
     */
    public var editable: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Optional row key.
         */id: String?,
        /**
         * Field name, already chosen.
         */label: String,
        /**
         * Field value, already formatted.
         */value: String,
        /**
         * Whether the shell may edit this row.
         */editable: Bool) {
        self.id = id
        self.label = label
        self.value = value
        self.editable = editable
    }




}

#if compiler(>=6)
extension FieldRow: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFieldRow: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FieldRow {
        return
            try FieldRow(
                id: FfiConverterOptionString.read(from: &buf),
                label: FfiConverterString.read(from: &buf),
                value: FfiConverterString.read(from: &buf),
                editable: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FieldRow, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.id, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
        FfiConverterBool.write(value.editable, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldRow_lift(_ buf: RustBuffer) throws -> FieldRow {
    return try FfiConverterTypeFieldRow.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldRow_lower(_ value: FieldRow) -> RustBuffer {
    return FfiConverterTypeFieldRow.lower(value)
}


/**
 * R6 role: command DTO.
 *
 * One editable structured postal address.
 */
public struct LabeledAddressDraft: Equatable, Hashable {
    /**
     * TYPE label.
     */
    public var label: String
    /**
     * Street.
     */
    public var street: String
    /**
     * City.
     */
    public var city: String
    /**
     * Region/state.
     */
    public var state: String
    /**
     * Postal code.
     */
    public var postalCode: String
    /**
     * Country.
     */
    public var country: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * TYPE label.
         */label: String,
        /**
         * Street.
         */street: String,
        /**
         * City.
         */city: String,
        /**
         * Region/state.
         */state: String,
        /**
         * Postal code.
         */postalCode: String,
        /**
         * Country.
         */country: String) {
        self.label = label
        self.street = street
        self.city = city
        self.state = state
        self.postalCode = postalCode
        self.country = country
    }




}

#if compiler(>=6)
extension LabeledAddressDraft: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLabeledAddressDraft: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LabeledAddressDraft {
        return
            try LabeledAddressDraft(
                label: FfiConverterString.read(from: &buf),
                street: FfiConverterString.read(from: &buf),
                city: FfiConverterString.read(from: &buf),
                state: FfiConverterString.read(from: &buf),
                postalCode: FfiConverterString.read(from: &buf),
                country: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: LabeledAddressDraft, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.street, into: &buf)
        FfiConverterString.write(value.city, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
        FfiConverterString.write(value.postalCode, into: &buf)
        FfiConverterString.write(value.country, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLabeledAddressDraft_lift(_ buf: RustBuffer) throws -> LabeledAddressDraft {
    return try FfiConverterTypeLabeledAddressDraft.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLabeledAddressDraft_lower(_ value: LabeledAddressDraft) -> RustBuffer {
    return FfiConverterTypeLabeledAddressDraft.lower(value)
}


/**
 * R6 role: command DTO.
 *
 * One editable labeled URL, phone, or email.
 */
public struct LabeledValueDraft: Equatable, Hashable {
    /**
     * TYPE label.
     */
    public var label: String
    /**
     * Unescaped value.
     */
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * TYPE label.
         */label: String,
        /**
         * Unescaped value.
         */value: String) {
        self.label = label
        self.value = value
    }




}

#if compiler(>=6)
extension LabeledValueDraft: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLabeledValueDraft: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LabeledValueDraft {
        return
            try LabeledValueDraft(
                label: FfiConverterString.read(from: &buf),
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: LabeledValueDraft, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLabeledValueDraft_lift(_ buf: RustBuffer) throws -> LabeledValueDraft {
    return try FfiConverterTypeLabeledValueDraft.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLabeledValueDraft_lower(_ value: LabeledValueDraft) -> RustBuffer {
    return FfiConverterTypeLabeledValueDraft.lower(value)
}


/**
 * R6 role: command DTO.
 *
 * Typed save intent carrying editable fields and their base token.
 */
public struct SaveContactCommand: Equatable, Hashable {
    /**
     * Draft to validate and save.
     */
    public var draft: ContactEditDraft

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Draft to validate and save.
         */draft: ContactEditDraft) {
        self.draft = draft
    }




}

#if compiler(>=6)
extension SaveContactCommand: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSaveContactCommand: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SaveContactCommand {
        return
            try SaveContactCommand(
                draft: FfiConverterTypeContactEditDraft.read(from: &buf)
        )
    }

    public static func write(_ value: SaveContactCommand, into buf: inout [UInt8]) {
        FfiConverterTypeContactEditDraft.write(value.draft, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSaveContactCommand_lift(_ buf: RustBuffer) throws -> SaveContactCommand {
    return try FfiConverterTypeSaveContactCommand.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSaveContactCommand_lower(_ value: SaveContactCommand) -> RustBuffer {
    return FfiConverterTypeSaveContactCommand.lower(value)
}


/**
 * One live-search match. Same slot as [`TextRow`]; `subtitle` is the
 * matched field value and `trailing` is the field kind.
 */
public struct SearchHit: Equatable, Hashable {
    /**
     * Opaque key the shell hands back.
     */
    public var id: String
    /**
     * Display name.
     */
    public var title: String
    /**
     * Matched field value; the shell highlights the query it already holds.
     */
    public var subtitle: String
    /**
     * Field kind (`Phone`, `Email`, …).
     */
    public var trailing: String?
    /**
     * Symbolic icon name for the matched field kind.
     */
    public var symbol: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Opaque key the shell hands back.
         */id: String,
        /**
         * Display name.
         */title: String,
        /**
         * Matched field value; the shell highlights the query it already holds.
         */subtitle: String,
        /**
         * Field kind (`Phone`, `Email`, …).
         */trailing: String?,
        /**
         * Symbolic icon name for the matched field kind.
         */symbol: String) {
        self.id = id
        self.title = title
        self.subtitle = subtitle
        self.trailing = trailing
        self.symbol = symbol
    }




}

#if compiler(>=6)
extension SearchHit: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchHit {
        return
            try SearchHit(
                id: FfiConverterString.read(from: &buf),
                title: FfiConverterString.read(from: &buf),
                subtitle: FfiConverterString.read(from: &buf),
                trailing: FfiConverterOptionString.read(from: &buf),
                symbol: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SearchHit, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.subtitle, into: &buf)
        FfiConverterOptionString.write(value.trailing, into: &buf)
        FfiConverterString.write(value.symbol, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lift(_ buf: RustBuffer) throws -> SearchHit {
    return try FfiConverterTypeSearchHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lower(_ value: SearchHit) -> RustBuffer {
    return FfiConverterTypeSearchHit.lower(value)
}


/**
 * `text-row` (ADR 0004 R4).
 */
public struct TextRow: Equatable, Hashable {
    /**
     * Opaque key the shell hands back.
     */
    public var id: String
    /**
     * Primary label.
     */
    public var title: String
    /**
     * Secondary label.
     */
    public var subtitle: String?
    /**
     * Trailing status.
     */
    public var trailing: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Opaque key the shell hands back.
         */id: String,
        /**
         * Primary label.
         */title: String,
        /**
         * Secondary label.
         */subtitle: String?,
        /**
         * Trailing status.
         */trailing: String?) {
        self.id = id
        self.title = title
        self.subtitle = subtitle
        self.trailing = trailing
    }




}

#if compiler(>=6)
extension TextRow: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTextRow: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TextRow {
        return
            try TextRow(
                id: FfiConverterString.read(from: &buf),
                title: FfiConverterString.read(from: &buf),
                subtitle: FfiConverterOptionString.read(from: &buf),
                trailing: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: TextRow, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.subtitle, into: &buf)
        FfiConverterOptionString.write(value.trailing, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextRow_lift(_ buf: RustBuffer) throws -> TextRow {
    return try FfiConverterTypeTextRow.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextRow_lower(_ value: TextRow) -> RustBuffer {
    return FfiConverterTypeTextRow.lower(value)
}


/**
 * Typed failures (ADR 0003 R8).
 */
public
enum ContactsError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    /**
     * Folder cannot be read or written.
     */
    case Io(
        /**
         * Log text, not a match key.
         */message: String
    )
    /**
     * No card or group with that id.
     */
    case NotFound
    /**
     * Merge needs a field choice; do not apply silently.
     */
    case NeedsChoice
    /**
     * Draft is older than the authoritative Card.
     */
    case StaleEdit(
        /**
         * Display-ready recovery message.
         */message: String,
        /**
         * The shell can recover by reopening the editor.
         */userActionable: Bool
    )
    /**
     * Typed command is inconsistent or invalid.
     */
    case InvalidCommand(
        /**
         * Display-ready validation message.
         */message: String,
        /**
         * The user can change the submitted values.
         */userActionable: Bool
    )






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension ContactsError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeContactsError: FfiConverterRustBuffer {
    typealias SwiftType = ContactsError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ContactsError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Io(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotFound
        case 3: return .NeedsChoice
        case 4: return .StaleEdit(
            message: try FfiConverterString.read(from: &buf),
            userActionable: try FfiConverterBool.read(from: &buf)
            )
        case 5: return .InvalidCommand(
            message: try FfiConverterString.read(from: &buf),
            userActionable: try FfiConverterBool.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ContactsError, into buf: inout [UInt8]) {
        switch value {





        case let .Io(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)


        case .NotFound:
            writeInt(&buf, Int32(2))


        case .NeedsChoice:
            writeInt(&buf, Int32(3))


        case let .StaleEdit(message,userActionable):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            FfiConverterBool.write(userActionable, into: &buf)


        case let .InvalidCommand(message,userActionable):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            FfiConverterBool.write(userActionable, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContactsError_lift(_ buf: RustBuffer) throws -> ContactsError {
    return try FfiConverterTypeContactsError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContactsError_lower(_ value: ContactsError) -> RustBuffer {
    return FfiConverterTypeContactsError.lower(value)
}


/**
 * Semantic conflict disposition. Shells use this for control flow.
 */

public enum MergeKind: Equatable, Hashable {

    /**
     * All fields merge deterministically.
     */
    case auto
    /**
     * At least one field requires a user choice.
     */
    case choice
    /**
     * The surviving file disappeared while a copy retains the data.
     */
    case deletedVersusModified





}

#if compiler(>=6)
extension MergeKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMergeKind: FfiConverterRustBuffer {
    typealias SwiftType = MergeKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MergeKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .auto

        case 2: return .choice

        case 3: return .deletedVersusModified

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MergeKind, into buf: inout [UInt8]) {
        switch value {


        case .auto:
            writeInt(&buf, Int32(1))


        case .choice:
            writeInt(&buf, Int32(2))


        case .deletedVersusModified:
            writeInt(&buf, Int32(3))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMergeKind_lift(_ buf: RustBuffer) throws -> MergeKind {
    return try FfiConverterTypeMergeKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMergeKind_lower(_ value: MergeKind) -> RustBuffer {
    return FfiConverterTypeMergeKind.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt32: FfiConverterRustBuffer {
    typealias SwiftType = Int32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeBirthdayDraft: FfiConverterRustBuffer {
    typealias SwiftType = BirthdayDraft?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeBirthdayDraft.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeBirthdayDraft.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeConflictFieldPreview: FfiConverterRustBuffer {
    typealias SwiftType = [ConflictFieldPreview]

    public static func write(_ value: [ConflictFieldPreview], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeConflictFieldPreview.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ConflictFieldPreview] {
        let len: Int32 = try readInt(&buf)
        var seq = [ConflictFieldPreview]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeConflictFieldPreview.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeConflictRow: FfiConverterRustBuffer {
    typealias SwiftType = [ConflictRow]

    public static func write(_ value: [ConflictRow], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeConflictRow.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ConflictRow] {
        let len: Int32 = try readInt(&buf)
        var seq = [ConflictRow]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeConflictRow.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeConflictSide: FfiConverterRustBuffer {
    typealias SwiftType = [ConflictSide]

    public static func write(_ value: [ConflictSide], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeConflictSide.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ConflictSide] {
        let len: Int32 = try readInt(&buf)
        var seq = [ConflictSide]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeConflictSide.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFieldRow: FfiConverterRustBuffer {
    typealias SwiftType = [FieldRow]

    public static func write(_ value: [FieldRow], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFieldRow.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FieldRow] {
        let len: Int32 = try readInt(&buf)
        var seq = [FieldRow]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFieldRow.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLabeledAddressDraft: FfiConverterRustBuffer {
    typealias SwiftType = [LabeledAddressDraft]

    public static func write(_ value: [LabeledAddressDraft], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLabeledAddressDraft.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LabeledAddressDraft] {
        let len: Int32 = try readInt(&buf)
        var seq = [LabeledAddressDraft]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLabeledAddressDraft.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLabeledValueDraft: FfiConverterRustBuffer {
    typealias SwiftType = [LabeledValueDraft]

    public static func write(_ value: [LabeledValueDraft], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLabeledValueDraft.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LabeledValueDraft] {
        let len: Int32 = try readInt(&buf)
        var seq = [LabeledValueDraft]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLabeledValueDraft.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchHit: FfiConverterRustBuffer {
    typealias SwiftType = [SearchHit]

    public static func write(_ value: [SearchHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchHit.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTextRow: FfiConverterRustBuffer {
    typealias SwiftType = [TextRow]

    public static func write(_ value: [TextRow], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTextRow.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TextRow] {
        let len: Int32 = try readInt(&buf)
        var seq = [TextRow]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTextRow.read(from: &buf))
        }
        return seq
    }
}
/**
 * Syncthing conflict-copy predicate (ADR 0005 R7).
 */
public func isConflictName(name: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_contacts_ffi_fn_func_is_conflict_name(
        FfiConverterString.lower(name),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_contacts_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_contacts_ffi_checksum_func_is_conflict_name() != 19151) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_assign_tag() != 3784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_conflict_choice_rows() != 60559) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_conflict_preview() != 9561) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_conflict_rows() != 55083) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_contact_edit_draft() != 36107) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_delete() != 58868) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_delete_many() != 62849) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_export_vcard_text() != 42388) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_field_rows() != 37331) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_file_name() != 13400) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_filtered_list_rows() != 43996) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_list_rows() != 25949) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_new_contact_draft() != 61206) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_reload() != 45278) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_remove_tag() != 6284) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_rename_tag() != 49562) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_resolve_group() != 6772) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_save_contact() != 10322) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_search_hits() != 57782) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_method_contactssession_tag_rows() != 33675) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_contacts_ffi_checksum_constructor_contactssession_open() != 60812) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureContactsFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
