//! Offline place names (ADR 0006 R10).
//!
//! `lookup` resolves a coordinate to a locality and a country with no
//! sockets and no HTTP. Country comes from admin-0 **point-in-polygon**.
//! Locality is the nearest packed city — which is not the containing
//! place, and must not decide the country (a photo just across a border
//! can be closer to a town on the other side).
//!
//! The committed pack is a GeoNames / Natural Earth **subset**: Paris
//! plus a Niagara River strip so the border test is real. Rebuild from
//! `cities1000` and NE admin-0 with `scripts/pack_geo.py` when the
//! network can carry those dumps. Licence text is in `ATTRIBUTION.md`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use std::collections::HashMap;
use std::sync::OnceLock;

mod pack;

use pack::{decode, City, Country, Pack};

/// Packed gazetteer + admin-0 rings. Generated by `scripts/pack_geo.py`.
const PACKED: &[u8] = include_bytes!("../data/places.bin");

/// One resolved place. `country` / `country_code` are from the containing
/// admin-0 polygon, never from the nearest city.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Place {
    /// Nearest packed populated place (GeoNames name).
    pub locality: String,
    /// Admin-1 name when the gazetteer row has one and that city sits
    /// in the same admin-0 country as the query point.
    pub admin: Option<String>,
    /// English country name from admin-0.
    pub country: String,
    /// ISO 3166-1 alpha-2, uppercase.
    pub country_code: String,
}

/// Well-known test point: Prospect Point, Niagara Falls, NY (US side).
pub const NIAGARA_US: (f64, f64) = (43.0828, -79.0610);
/// Well-known test point: Table Rock, Niagara Falls, ON (Canada side).
pub const NIAGARA_CA: (f64, f64) = (43.0896, -79.0789);
/// Hôtel de Ville / Île de la Cité, Paris.
pub const PARIS: (f64, f64) = (48.8566, 2.3522);

struct Index {
    pack: Pack,
    /// 1° cells → city indices. Sparse: only occupied cells are stored.
    grid: HashMap<(i16, i16), Vec<usize>>,
}

impl Index {
    fn load() -> Self {
        let pack = decode(PACKED).expect("committed geo pack must decode");
        let mut grid: HashMap<(i16, i16), Vec<usize>> = HashMap::new();
        for (i, city) in pack.cities.iter().enumerate() {
            grid.entry(cell(city.lat, city.lon)).or_default().push(i);
        }
        Self { pack, grid }
    }
}

fn atlas() -> &'static Index {
    static ATLAS: OnceLock<Index> = OnceLock::new();
    ATLAS.get_or_init(Index::load)
}

/// Cell of a 1° grid. `floor` so 43.9 and −79.1 land in (43, −80).
fn cell(lat: f64, lon: f64) -> (i16, i16) {
    (lat.floor() as i16, lon.floor() as i16)
}

/// Haversine kilometres. Same earth radius as the former gallery cache.
fn haversine_km(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    const R: f64 = 6371.0;
    let p1 = lat1.to_radians();
    let p2 = lat2.to_radians();
    let dp = (lat2 - lat1).to_radians();
    let dl = (lon2 - lon1).to_radians();
    let a = (dp / 2.0).sin().powi(2) + p1.cos() * p2.cos() * (dl / 2.0).sin().powi(2);
    2.0 * R * a.sqrt().atan2((1.0 - a).sqrt())
}

/// Even-odd ray cast. `ring` is (lon, lat), not required to repeat the
/// first vertex.
fn point_in_ring(lon: f64, lat: f64, ring: &[(f64, f64)]) -> bool {
    if ring.len() < 3 {
        return false;
    }
    let mut inside = false;
    let mut j = ring.len() - 1;
    for i in 0..ring.len() {
        let (xi, yi) = ring[i];
        let (xj, yj) = ring[j];
        if (yi > lat) != (yj > lat) {
            let xint = (xj - xi) * (lat - yi) / (yj - yi) + xi;
            if lon < xint {
                inside = !inside;
            }
        }
        j = i;
    }
    inside
}

fn country_at(countries: &[Country], lat: f64, lon: f64) -> Option<&Country> {
    countries.iter().find(|c| {
        if lon < c.min_lon || lon > c.max_lon || lat < c.min_lat || lat > c.max_lat {
            return false;
        }
        c.rings.iter().any(|ring| point_in_ring(lon, lat, ring))
    })
}

/// Nearest city in this cell and its 8 neighbours, then a growing
/// window if the 3×3 is empty. At subset scale the window is plenty;
/// a full `cities1000` pack still hits a handful of records per query.
fn nearest_city<'a>(index: &'a Index, lat: f64, lon: f64) -> Option<&'a City> {
    let (ci, cj) = cell(lat, lon);
    let mut best: Option<(&City, f64)> = None;
    for radius in 0i16..=8 {
        for di in -radius..=radius {
            for dj in -radius..=radius {
                if radius > 0 && di.abs() != radius && dj.abs() != radius {
                    continue;
                }
                let Some(hits) = index.grid.get(&(ci + di, cj + dj)) else {
                    continue;
                };
                for &k in hits {
                    let city = &index.pack.cities[k];
                    let d = haversine_km(lat, lon, city.lat, city.lon);
                    if best.map(|(_, bd)| d < bd).unwrap_or(true) {
                        best = Some((city, d));
                    }
                }
            }
        }
        if best.is_some() {
            break;
        }
    }
    best.map(|(c, _)| c)
}

/// Nearest packed city and the admin-0 country that contains `(lat, lon)`.
///
/// `None` when the point is not inside a packed country ring (ocean,
/// or a state the subset omitted). Country is never taken from the city.
pub fn lookup(lat: f64, lon: f64) -> Option<Place> {
    if !lat.is_finite() || !lon.is_finite() || !(-90.0..=90.0).contains(&lat) {
        return None;
    }
    let index = atlas();
    let country = country_at(&index.pack.countries, lat, lon)?;
    let city = nearest_city(index, lat, lon)?;
    let same_country = country_at(&index.pack.countries, city.lat, city.lon)
        .is_some_and(|c| c.code == country.code);
    Some(Place {
        locality: city.locality.clone(),
        admin: if same_country {
            city.admin.clone()
        } else {
            None
        },
        country: country.name.clone(),
        country_code: std::str::from_utf8(&country.code)
            .expect("pack validated A-Z")
            .to_owned(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn packed_subset_is_under_10mb() {
        assert!(
            PACKED.len() < 10 * 1024 * 1024,
            "committed pack is {} bytes",
            PACKED.len()
        );
        assert!(PACKED.len() > 64, "pack looks empty");
    }

    #[test]
    fn paris_locality() {
        let p = lookup(PARIS.0, PARIS.1).expect("Paris is in the subset");
        assert_eq!(p.locality, "Paris");
        assert_eq!(p.admin.as_deref(), Some("Île-de-France"));
        assert_eq!(p.country, "France");
        assert_eq!(p.country_code, "FR");
    }

    #[test]
    fn niagara_border_countries_differ() {
        let us = lookup(NIAGARA_US.0, NIAGARA_US.1).expect("US bank");
        let ca = lookup(NIAGARA_CA.0, NIAGARA_CA.1).expect("Canadian bank");
        assert_eq!(us.country_code, "US", "{us:?}");
        assert_eq!(ca.country_code, "CA", "{ca:?}");
        assert_ne!(us.country_code, ca.country_code);
        assert_eq!(us.country, "United States");
        assert_eq!(ca.country, "Canada");
    }

    #[test]
    fn niagara_country_is_polygon_not_nearest_city() {
        // Table Rock is closer to Niagara Falls, NY than to Toronto.
        // If country came from the city row it would be US.
        let ca = lookup(NIAGARA_CA.0, NIAGARA_CA.1).unwrap();
        let ny = atlas()
            .pack
            .cities
            .iter()
            .find(|c| c.locality == "Niagara Falls")
            .unwrap();
        let toronto = atlas()
            .pack
            .cities
            .iter()
            .find(|c| c.locality == "Toronto")
            .unwrap();
        let d_ny = haversine_km(NIAGARA_CA.0, NIAGARA_CA.1, ny.lat, ny.lon);
        let d_to = haversine_km(NIAGARA_CA.0, NIAGARA_CA.1, toronto.lat, toronto.lon);
        assert!(
            d_ny < d_to,
            "fixture broken: Canadian point should be nearer NY city ({d_ny}) than Toronto ({d_to})"
        );
        assert_eq!(ca.locality, "Niagara Falls");
        assert_eq!(ca.country_code, "CA");
        assert_eq!(
            ca.admin.as_deref(),
            None,
            "must not copy NY admin onto a Canadian PIP hit"
        );
    }

    #[test]
    fn ocean_is_none() {
        assert!(lookup(40.0, -30.0).is_none());
    }

    #[test]
    fn garbage_coordinates_are_none() {
        assert!(lookup(f64::NAN, 0.0).is_none());
        assert!(lookup(91.0, 0.0).is_none());
    }
}
