#!/usr/bin/env python3
"""Check or regenerate scripts/build_model_pack/requirements.lock.

The lock lists sha256 hashes for every published artifact of each *direct*
pin in requirements.txt. It is not a full transitive hash-lock (pip's
--require-hashes needs those, and they are platform-specific).

    python3 lock_requirements.py --check
    python3 lock_requirements.py --write   # needs network (PyPI JSON)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
REQ = HERE / "requirements.txt"
LOCK = HERE / "requirements.lock"

PIN_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([0-9A-Za-z_.+-]+)")


def parse_requirements(path: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        m = PIN_RE.match(line)
        if not m:
            continue
        pins[m.group(1)] = m.group(2)
    return pins


def parse_lock(path: Path) -> dict[str, tuple[str, list[str]]]:
    """name -> (version, [sha256, ...])."""
    text = path.read_text()
    current: str | None = None
    out: dict[str, tuple[str, list[str]]] = {}
    hashes: list[str] = []
    version = ""
    for raw in text.splitlines():
        line = raw.strip().rstrip("\\").strip()
        if not line or line.startswith("#"):
            continue
        m = PIN_RE.match(line)
        if m:
            if current:
                out[current] = (version, hashes)
            current = m.group(1)
            version = m.group(2)
            hashes = []
            continue
        if line.startswith("--hash=sha256:"):
            hashes.append(line.split(":", 1)[1])
    if current:
        out[current] = (version, hashes)
    return out


def pypi_files(name: str, version: str) -> list[tuple[str, str]]:
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=60) as resp:
        data = json.load(resp)
    files = []
    for item in data.get("urls", []):
        files.append((item["filename"], item["digests"]["sha256"]))
    if not files:
        raise SystemExit(f"no PyPI artifacts for {name}=={version}")
    return files


def write_lock(pins: dict[str, str]) -> None:
    lines = [
        "# Hashed pins for the direct model-pack dependencies in requirements.txt.",
        "# Regenerated by lock_requirements.py --write from PyPI JSON.",
        "#",
        "# Direct deps only. pip --require-hashes also wants transitive wheels.",
        "# Install with `pip install -r requirements.txt`; verify with --check.",
        "",
    ]
    for name, version in pins.items():
        files = pypi_files(name, version)
        print(f"{name}=={version}  {len(files)} artifacts", file=sys.stderr)
        lines.append(f"{name}=={version} \\")
        hashes = [f"    --hash=sha256:{digest}" for _, digest in files]
        for i, h in enumerate(hashes):
            lines.append(h + ("" if i == len(hashes) - 1 else " \\"))
        lines.append("")
    LOCK.write_text("\n".join(lines) + "\n")
    print(f"wrote {LOCK}", file=sys.stderr)


def check(pins: dict[str, str]) -> int:
    if not LOCK.is_file():
        print(f"error: missing {LOCK}", file=sys.stderr)
        return 1
    locked = parse_lock(LOCK)
    errors = 0
    for name, version in pins.items():
        if name not in locked:
            print(f"error: {name}=={version} not in {LOCK.name}", file=sys.stderr)
            errors += 1
            continue
        lock_ver, hashes = locked[name]
        if lock_ver != version:
            print(
                f"error: {name} pin {version} != lock {lock_ver}",
                file=sys.stderr,
            )
            errors += 1
        if len(hashes) < 1:
            print(f"error: {name} has no hashes in {LOCK.name}", file=sys.stderr)
            errors += 1
        if len(set(hashes)) != len(hashes):
            print(f"error: {name} has duplicate hashes", file=sys.stderr)
            errors += 1
    extra = sorted(set(locked) - set(pins))
    if extra:
        print(f"error: lock has extra packages: {extra}", file=sys.stderr)
        errors += 1
    if errors:
        return 1
    print(
        f"ok: {len(pins)} direct pins match {LOCK.name} "
        f"({sum(len(locked[n][1]) for n in pins)} artifact hashes)"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify lock vs requirements.txt")
    parser.add_argument("--write", action="store_true", help="regenerate lock from PyPI")
    args = parser.parse_args()
    pins = parse_requirements(REQ)
    if not pins:
        print(f"error: no == pins in {REQ}", file=sys.stderr)
        return 1
    if args.write:
        write_lock(pins)
        return 0
    return check(pins)


if __name__ == "__main__":
    sys.exit(main())
