#!/usr/bin/env python3
"""ADR 0004 R14 — generate slot-kind enums and design tokens.

Inputs:
  docs/spec/ui/vocabulary.toml
  design/tokens/{gallery,contacts,music,health}.toml

Outputs (reproducible; --check fails on drift):
  core/localcore-ui/src/kinds.rs
  core/localcore-ui/src/tokens.rs
  docs/spec/ui/generated/Kinds.swift
  apps/{gallery,contacts,music}/.../Generated/Tokens.swift
  design/tokens/generated/{app}.css
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
VOCAB = REPO / "docs/spec/ui/vocabulary.toml"
TOKENS_DIR = REPO / "design/tokens"
APPS = ("gallery", "contacts", "music", "health")

SWIFT_KINDS = REPO / "docs/spec/ui/generated/Kinds.swift"
RUST_KINDS = REPO / "core/localcore-ui/src/kinds.rs"
RUST_TOKENS = REPO / "core/localcore-ui/src/tokens.rs"

TOKEN_SWIFT = {
    "gallery": REPO / "apps/gallery/LocalGallery/Generated/Tokens.swift",
    "contacts": REPO / "apps/contacts/LocalContacts/Generated/Tokens.swift",
    "music": REPO / "apps/music/LocalMusic/Generated/Tokens.swift",
}


def pascal(name: str) -> str:
    return "".join(p.title() for p in name.replace("_", "-").split("-"))


def camel(name: str) -> str:
    ident = pascal(name)
    return ident[0].lower() + ident[1:]


def snake(name: str) -> str:
    return name.replace("-", "_")


def hex_to_rgb(value: str) -> tuple[int, int, int]:
    h = value.removeprefix("#")
    if len(h) != 6:
        raise ValueError(f"expected #RRGGBB, got {value!r}")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def swift_rgb(value: str) -> str:
    r, g, b = hex_to_rgb(value)
    return (
        f"Color(red: {r / 255:.3f}, green: {g / 255:.3f}, blue: {b / 255:.3f})"
    )


def rust_enum(name: str, variants: list[str]) -> str:
    arms = "\n".join(f"    {pascal(v)}," for v in variants)
    matches = "\n".join(
        f'            Self::{pascal(v)} => "{v}",' for v in variants
    )
    all_inner = ", ".join(f"Self::{pascal(v)}" for v in variants)
    all_one = f"    pub const ALL: &'static [Self] = &[{all_inner}];"
    if len(all_one) <= 100:
        all_decl = all_one
    else:
        all_decl = (
            "    pub const ALL: &'static [Self] = &[\n        "
            + ",\n        ".join(f"Self::{pascal(v)}" for v in variants)
            + ",\n    ];"
        )
    return f"""#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum {name} {{
{arms}
}}

impl {name} {{
{all_decl}

    pub fn as_str(self) -> &'static str {{
        match self {{
{matches}
        }}
    }}
}}
"""


def swift_enum(name: str, variants: list[str]) -> str:
    cases = "\n".join(f'    case {camel(v)} = "{v}"' for v in variants)
    return f"""public enum {name}: String, Sendable, CaseIterable {{
{cases}
}}
"""


def generate_kinds(vocab: dict) -> tuple[str, str]:
    tables = [
        ("ScreenKind", vocab["screen_kinds"]),
        ("ItemKind", vocab["item_kinds"]),
        ("Affordance", vocab["affordances"]),
        ("NavIntent", vocab["nav_intents"]),
        ("ActionRole", vocab["action_roles"]),
        ("StatusSeverity", vocab["status_severities"]),
    ]
    rust = (
        "//! Generated by `scripts/gen_r14.py`. Do not edit.\n"
        "//! ADR 0004 R4 closed vocabulary.\n\n"
    )
    rust += "\n".join(rust_enum(n, vs) for n, vs in tables)
    swift = (
        "// Generated by scripts/gen_r14.py. Do not edit.\n"
        "// ADR 0004 R4 closed vocabulary.\n\n"
    )
    swift += "\n".join(swift_enum(n, vs) for n, vs in tables)
    if not swift.endswith("\n"):
        swift += "\n"
    return rust, swift


def generate_tokens_rs(tables: dict[str, dict]) -> str:
    lines = [
        "//! Generated by `scripts/gen_r14.py`. Do not edit.",
        "//! ADR 0004 R11 token tables. Hex strings; no UI toolkit.",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct ColorHex {",
        "    pub light: &'static str,",
        "    pub dark: Option<&'static str>,",
        "}",
        "",
    ]
    for app, table in tables.items():
        colors = table.get("colors", {})
        has_color = any(spec.get("light") for spec in colors.values())
        lines.append(f"pub mod {app} {{")
        if has_color:
            lines.append("    use super::ColorHex;")
        for role, spec in colors.items():
            const = snake(role).upper()
            light = spec.get("light")
            if not light:
                continue
            dark = spec.get("dark")
            dark_rs = f'Some("{dark}")' if dark else "None"
            lines.append(f"    pub const {const}: ColorHex = ColorHex {{")
            lines.append(f'        light: "{light}",')
            lines.append(f"        dark: {dark_rs},")
            lines.append("    };")
        for name, value in table.get("metrics", {}).items():
            const = snake(name).upper()
            if isinstance(value, float):
                lines.append(f"    pub const {const}: f64 = {value};")
            else:
                lines.append(f"    pub const {const}: f64 = {value}.0;")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def generate_tokens_swift(app: str, table: dict) -> str:
    colors = table.get("colors", {})
    metrics = table.get("metrics", {})
    needs_adaptive = any("dark" in spec for spec in colors.values())
    lines = [
        f"// Generated by scripts/gen_r14.py from design/tokens/{app}.toml. "
        "Do not edit.",
        "import SwiftUI",
        "",
        f"enum {pascal(app)}Tokens {{",
    ]
    for role, spec in colors.items():
        ident = camel(role)
        light = spec.get("light")
        if not light:
            continue
        dark = spec.get("dark")
        if dark:
            lines.append(
                f"    static let {ident} = Color(light: {swift_rgb(light)}, "
                f"dark: {swift_rgb(dark)})"
            )
        else:
            lines.append(f"    static let {ident} = {swift_rgb(light)}")
    for name, value in metrics.items():
        ident = camel(name)
        if isinstance(value, float):
            lines.append(f"    static let {ident}: Double = {value}")
        else:
            lines.append(f"    static let {ident}: CGFloat = {value}")
    lines.append("}")
    if needs_adaptive:
        lines.append("")
        lines.append("#if canImport(UIKit)")
        lines.append("import UIKit")
        lines.append("")
        lines.append("private extension Color {")
        lines.append("    init(light: Color, dark: Color) {")
        lines.append("        self.init(uiColor: UIColor { traits in")
        lines.append(
            "            traits.userInterfaceStyle == .dark"
        )
        lines.append("                ? UIColor(dark)")
        lines.append("                : UIColor(light)")
        lines.append("        })")
        lines.append("    }")
        lines.append("}")
        lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def generate_tokens_css(app: str, table: dict) -> str | None:
    colors = table.get("colors", {})
    metrics = table.get("metrics", {})
    if not colors and not metrics:
        return None
    lines = [
        f"/* Generated by scripts/gen_r14.py from design/tokens/{app}.toml. "
        "Do not edit. */",
        ":root {",
    ]
    dark_lines: list[str] = []
    for role, spec in colors.items():
        ident = snake(role).replace("_", "-")
        if "light" in spec:
            lines.append(f"  --{ident}: {spec['light']};")
        if "dark" in spec:
            dark_lines.append(f"    --{ident}: {spec['dark']};")
    for name, value in metrics.items():
        ident = snake(name).replace("_", "-")
        if isinstance(value, float):
            lines.append(f"  --{ident}: {value};")
        else:
            lines.append(f"  --{ident}: {value}px;")
    lines.append("}")
    if dark_lines:
        lines.append("")
        lines.append("@media (prefers-color-scheme: dark) {")
        lines.append("  :root {")
        lines.extend(dark_lines)
        lines.append("  }")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)


def generate_all() -> dict[Path, str]:
    vocab = tomllib.loads(VOCAB.read_text())
    rust_kinds, swift_kinds = generate_kinds(vocab)
    tables = {
        app: tomllib.loads((TOKENS_DIR / f"{app}.toml").read_text())
        for app in APPS
    }
    out: dict[Path, str] = {
        RUST_KINDS: rust_kinds,
        RUST_TOKENS: generate_tokens_rs(tables),
        SWIFT_KINDS: swift_kinds,
    }
    for app, table in tables.items():
        if app in TOKEN_SWIFT:
            out[TOKEN_SWIFT[app]] = generate_tokens_swift(app, table)
        css = generate_tokens_css(app, table)
        if css is not None:
            out[TOKENS_DIR / "generated" / f"{app}.css"] = css
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="succeed only when generated files already match",
    )
    args = parser.parse_args(argv)
    planned = generate_all()
    if args.check:
        drifted = []
        for path, body in planned.items():
            if not path.is_file() or path.read_text() != body:
                drifted.append(str(path.relative_to(REPO)))
        if drifted:
            print("error: R14 generated sources drifted:", file=sys.stderr)
            for p in drifted:
                print(f"  {p}", file=sys.stderr)
            print("run: python3 scripts/gen_r14.py", file=sys.stderr)
            return 1
        print("R14 generated sources match")
        return 0
    for path, body in planned.items():
        write(path, body)
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
