//! Generated by `scripts/gen_r14.py`. Do not edit.
//! ADR 0004 R4 closed vocabulary.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ScreenKind {
    List,
    Grid,
    Detail,
    Form,
    Viewer,
    Settings,
}

impl ScreenKind {
    pub const ALL: &'static [Self] = &[
        Self::List,
        Self::Grid,
        Self::Detail,
        Self::Form,
        Self::Viewer,
        Self::Settings,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::List => "list",
            Self::Grid => "grid",
            Self::Detail => "detail",
            Self::Form => "form",
            Self::Viewer => "viewer",
            Self::Settings => "settings",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ItemKind {
    TextRow,
    MediaItem,
    FieldRow,
    ToggleRow,
    ActionRow,
    NavRow,
    ProgressRow,
    StatusRow,
    ChartRow,
}

impl ItemKind {
    pub const ALL: &'static [Self] = &[
        Self::TextRow,
        Self::MediaItem,
        Self::FieldRow,
        Self::ToggleRow,
        Self::ActionRow,
        Self::NavRow,
        Self::ProgressRow,
        Self::StatusRow,
        Self::ChartRow,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::TextRow => "text-row",
            Self::MediaItem => "media-item",
            Self::FieldRow => "field-row",
            Self::ToggleRow => "toggle-row",
            Self::ActionRow => "action-row",
            Self::NavRow => "nav-row",
            Self::ProgressRow => "progress-row",
            Self::StatusRow => "status-row",
            Self::ChartRow => "chart-row",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Affordance {
    Search,
    Filter,
    Sort,
    Selection,
    PrimaryAction,
    Overflow,
    Banner,
    Progress,
    Confirm,
}

impl Affordance {
    pub const ALL: &'static [Self] = &[
        Self::Search,
        Self::Filter,
        Self::Sort,
        Self::Selection,
        Self::PrimaryAction,
        Self::Overflow,
        Self::Banner,
        Self::Progress,
        Self::Confirm,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Search => "search",
            Self::Filter => "filter",
            Self::Sort => "sort",
            Self::Selection => "selection",
            Self::PrimaryAction => "primary-action",
            Self::Overflow => "overflow",
            Self::Banner => "banner",
            Self::Progress => "progress",
            Self::Confirm => "confirm",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NavIntent {
    Push,
    Sheet,
    Replace,
}

impl NavIntent {
    pub const ALL: &'static [Self] = &[Self::Push, Self::Sheet, Self::Replace];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Push => "push",
            Self::Sheet => "sheet",
            Self::Replace => "replace",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ActionRole {
    Normal,
    Destructive,
}

impl ActionRole {
    pub const ALL: &'static [Self] = &[Self::Normal, Self::Destructive];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Normal => "normal",
            Self::Destructive => "destructive",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StatusSeverity {
    Info,
    Warning,
    Error,
}

impl StatusSeverity {
    pub const ALL: &'static [Self] = &[Self::Info, Self::Warning, Self::Error];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Info => "info",
            Self::Warning => "warning",
            Self::Error => "error",
        }
    }
}
