//! ADR 0004 vocabulary, screen identifiers, and design tokens.
//!
//! Generated by `scripts/gen_r14.py`. No UI-toolkit dependency
//! (ADR 0001 R9).

mod kinds;
mod screens;
mod tokens;

pub use kinds::{ActionRole, Affordance, ItemKind, NavIntent, ScreenKind, StatusSeverity};
pub use screens::{ContactsScreen, GalleryScreen, HealthScreen, MusicScreen};

pub mod gallery {
    pub use crate::tokens::gallery::*;
}

pub mod contacts {
    pub use crate::tokens::contacts::*;
}

pub mod music {
    pub use crate::tokens::music::*;
}

pub mod health {
    pub use crate::tokens::health::*;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn r4_screen_kinds() {
        assert_eq!(ScreenKind::ALL.len(), 6);
        assert_eq!(ScreenKind::List.as_str(), "list");
        assert_eq!(ItemKind::TextRow.as_str(), "text-row");
        assert_eq!(ItemKind::ChartRow.as_str(), "chart-row");
        assert_eq!(Affordance::PrimaryAction.as_str(), "primary-action");
        assert_eq!(NavIntent::Push.as_str(), "push");
    }

    #[test]
    fn sourced_dark_accents() {
        assert_eq!(gallery::ACCENT, "#C48A3E");
        assert_eq!(gallery::ACCENT_DARK, "#D4994D");
        assert_eq!(contacts::ACCENT, "#336BC7");
        assert_eq!(contacts::ACCENT_DARK, "#4D85DE");
        assert_eq!(music::ACCENT, "#C0392B");
        assert_eq!(music::ACCENT_DARK, "#D14738");
    }

    #[test]
    fn contacts_screens_match_the_spec() {
        assert!(ContactsScreen::ALL.len() >= 8);
        assert_eq!(ContactsScreen::ContactList.as_str(), "contact-list");
        assert_eq!(ContactsScreen::ContactList.kind(), ScreenKind::List);
        assert_eq!(ContactsScreen::ContactEdit.kind(), ScreenKind::Form);
        assert_eq!(ContactsScreen::SyncConflictGroup.kind(), ScreenKind::Detail);
    }

    #[test]
    fn gallery_screens_match_the_spec() {
        assert_eq!(GalleryScreen::ALL.len(), 16);
        assert_eq!(GalleryScreen::Photos.as_str(), "photos");
        assert_eq!(GalleryScreen::Photos.kind(), ScreenKind::Grid);
        assert_eq!(GalleryScreen::FaceReview.kind(), ScreenKind::List);
        assert_eq!(GalleryScreen::Viewer.kind(), ScreenKind::Viewer);
    }

    #[test]
    fn music_screens_match_the_spec() {
        assert_eq!(MusicScreen::ALL.len(), 9);
        assert_eq!(MusicScreen::Library.as_str(), "library");
        assert_eq!(MusicScreen::Library.kind(), ScreenKind::List);
        assert_eq!(MusicScreen::NowPlaying.kind(), ScreenKind::Viewer);
        assert_eq!(MusicScreen::SyncConflictGroup.kind(), ScreenKind::Detail);
    }

    #[test]
    fn health_screens_match_the_spec() {
        assert_eq!(HealthScreen::ALL.len(), 9);
        assert_eq!(HealthScreen::KindDetail.as_str(), "kind-detail");
        assert_eq!(HealthScreen::KindDetail.kind(), ScreenKind::Detail);
        assert_eq!(HealthScreen::Gaps.kind(), ScreenKind::List);
        assert!(health::CARD_RADIUS > 0.0);
    }
}
