//! ADR 0004 vocabulary, screen identifiers, and design tokens.
//!
//! Generated by `scripts/gen_r14.py`. No UI-toolkit dependency
//! (ADR 0001 R9).

mod kinds;
mod screens;
mod tokens;

pub use kinds::{ActionRole, Affordance, ItemKind, NavIntent, ScreenKind, StatusSeverity};
pub use screens::ContactsScreen;

pub mod gallery {
    pub use crate::tokens::gallery::*;
}

pub mod contacts {
    pub use crate::tokens::contacts::*;
}

pub mod music {
    pub use crate::tokens::music::*;
}

pub mod health {
    pub use crate::tokens::health::*;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn r4_screen_kinds() {
        assert_eq!(ScreenKind::ALL.len(), 6);
        assert_eq!(ScreenKind::List.as_str(), "list");
        assert_eq!(ItemKind::TextRow.as_str(), "text-row");
        assert_eq!(Affordance::PrimaryAction.as_str(), "primary-action");
        assert_eq!(NavIntent::Push.as_str(), "push");
    }

    #[test]
    fn gallery_accent_is_light_only() {
        assert_eq!(gallery::ACCENT, "#C48A3E");
    }

    #[test]
    fn contacts_screens_match_the_spec() {
        assert!(ContactsScreen::ALL.len() >= 8);
        assert_eq!(ContactsScreen::ContactList.as_str(), "contact-list");
        assert_eq!(ContactsScreen::ContactList.kind(), ScreenKind::List);
        assert_eq!(ContactsScreen::ContactEdit.kind(), ScreenKind::Form);
        assert_eq!(ContactsScreen::SyncConflictGroup.kind(), ScreenKind::Detail);
    }
}
