//! ADR 0004 vocabulary and design tokens.
//!
//! Kinds and token tables are generated by `scripts/gen_r14.py` from
//! `docs/spec/ui/vocabulary.toml` and `design/tokens/*.toml`. This crate
//! has no UI-toolkit dependency (ADR 0001 R9).

mod kinds;
mod tokens;

pub use kinds::{ActionRole, Affordance, ItemKind, NavIntent, ScreenKind, StatusSeverity};
pub use tokens::ColorHex;

pub mod gallery {
    pub use crate::tokens::gallery::*;
}

pub mod contacts {
    pub use crate::tokens::contacts::*;
}

pub mod music {
    pub use crate::tokens::music::*;
}

pub mod health {
    pub use crate::tokens::health::*;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn r4_screen_kinds() {
        assert_eq!(ScreenKind::ALL.len(), 6);
        assert_eq!(ScreenKind::List.as_str(), "list");
        assert_eq!(ItemKind::TextRow.as_str(), "text-row");
        assert_eq!(Affordance::PrimaryAction.as_str(), "primary-action");
        assert_eq!(NavIntent::Push.as_str(), "push");
    }

    #[test]
    fn gallery_accent_is_the_colorset() {
        assert_eq!(gallery::ACCENT.light, "#C48A3E");
        assert_eq!(gallery::ACCENT.dark, Some("#D4994D"));
        assert!(gallery::BG.dark.is_none(), "dark surfaces are unauthored");
    }
}
