//! Generated by `scripts/gen_r14.py`. Do not edit.
//! Per-app screen identifiers (ADR 0004 R14).

use crate::ScreenKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ContactsScreen {
    FolderPicker,
    ContactList,
    ContactDetail,
    ContactEdit,
    Settings,
    TagManagement,
    Logs,
    AppleConflict,
    SyncConflictGroup,
}

impl ContactsScreen {
    pub const ALL: &'static [Self] = &[
        Self::FolderPicker,
        Self::ContactList,
        Self::ContactDetail,
        Self::ContactEdit,
        Self::Settings,
        Self::TagManagement,
        Self::Logs,
        Self::AppleConflict,
        Self::SyncConflictGroup,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::FolderPicker => "folder-picker",
            Self::ContactList => "contact-list",
            Self::ContactDetail => "contact-detail",
            Self::ContactEdit => "contact-edit",
            Self::Settings => "settings",
            Self::TagManagement => "tag-management",
            Self::Logs => "logs",
            Self::AppleConflict => "apple-conflict",
            Self::SyncConflictGroup => "sync-conflict-group",
        }
    }

    pub fn kind(self) -> ScreenKind {
        match self {
            Self::FolderPicker => ScreenKind::Detail,
            Self::ContactList => ScreenKind::List,
            Self::ContactDetail => ScreenKind::Detail,
            Self::ContactEdit => ScreenKind::Form,
            Self::Settings => ScreenKind::Settings,
            Self::TagManagement => ScreenKind::List,
            Self::Logs => ScreenKind::List,
            Self::AppleConflict => ScreenKind::Detail,
            Self::SyncConflictGroup => ScreenKind::Detail,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HealthScreen {
    Today,
    Medicine,
    Lifestyle,
    Sports,
    AllKinds,
    KindDetail,
    WorkoutSession,
    Gaps,
    SourceFiles,
}

impl HealthScreen {
    pub const ALL: &'static [Self] = &[
        Self::Today,
        Self::Medicine,
        Self::Lifestyle,
        Self::Sports,
        Self::AllKinds,
        Self::KindDetail,
        Self::WorkoutSession,
        Self::Gaps,
        Self::SourceFiles,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Today => "today",
            Self::Medicine => "medicine",
            Self::Lifestyle => "lifestyle",
            Self::Sports => "sports",
            Self::AllKinds => "all-kinds",
            Self::KindDetail => "kind-detail",
            Self::WorkoutSession => "workout-session",
            Self::Gaps => "gaps",
            Self::SourceFiles => "source-files",
        }
    }

    pub fn kind(self) -> ScreenKind {
        match self {
            Self::Today => ScreenKind::List,
            Self::Medicine => ScreenKind::List,
            Self::Lifestyle => ScreenKind::List,
            Self::Sports => ScreenKind::List,
            Self::AllKinds => ScreenKind::List,
            Self::KindDetail => ScreenKind::Detail,
            Self::WorkoutSession => ScreenKind::Detail,
            Self::Gaps => ScreenKind::List,
            Self::SourceFiles => ScreenKind::List,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MusicScreen {
    FolderPicker,
    Library,
    PlaylistList,
    PlaylistDetail,
    AddTracks,
    NowPlaying,
    Settings,
    Logs,
    SyncConflictGroup,
}

impl MusicScreen {
    pub const ALL: &'static [Self] = &[
        Self::FolderPicker,
        Self::Library,
        Self::PlaylistList,
        Self::PlaylistDetail,
        Self::AddTracks,
        Self::NowPlaying,
        Self::Settings,
        Self::Logs,
        Self::SyncConflictGroup,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::FolderPicker => "folder-picker",
            Self::Library => "library",
            Self::PlaylistList => "playlist-list",
            Self::PlaylistDetail => "playlist-detail",
            Self::AddTracks => "add-tracks",
            Self::NowPlaying => "now-playing",
            Self::Settings => "settings",
            Self::Logs => "logs",
            Self::SyncConflictGroup => "sync-conflict-group",
        }
    }

    pub fn kind(self) -> ScreenKind {
        match self {
            Self::FolderPicker => ScreenKind::Detail,
            Self::Library => ScreenKind::List,
            Self::PlaylistList => ScreenKind::List,
            Self::PlaylistDetail => ScreenKind::Detail,
            Self::AddTracks => ScreenKind::List,
            Self::NowPlaying => ScreenKind::Viewer,
            Self::Settings => ScreenKind::Settings,
            Self::Logs => ScreenKind::List,
            Self::SyncConflictGroup => ScreenKind::Detail,
        }
    }
}
