//! Generated by `scripts/gen_r14.py`. Do not edit.
//! Per-app screen identifiers (ADR 0004 R14).

use crate::ScreenKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ContactsScreen {
    FolderPicker,
    ContactList,
    ContactDetail,
    ContactEdit,
    Settings,
    TagManagement,
    Logs,
    AppleConflict,
    SyncConflictGroup,
}

impl ContactsScreen {
    pub const ALL: &'static [Self] = &[
        Self::FolderPicker,
        Self::ContactList,
        Self::ContactDetail,
        Self::ContactEdit,
        Self::Settings,
        Self::TagManagement,
        Self::Logs,
        Self::AppleConflict,
        Self::SyncConflictGroup,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::FolderPicker => "folder-picker",
            Self::ContactList => "contact-list",
            Self::ContactDetail => "contact-detail",
            Self::ContactEdit => "contact-edit",
            Self::Settings => "settings",
            Self::TagManagement => "tag-management",
            Self::Logs => "logs",
            Self::AppleConflict => "apple-conflict",
            Self::SyncConflictGroup => "sync-conflict-group",
        }
    }

    pub fn kind(self) -> ScreenKind {
        match self {
            Self::FolderPicker => ScreenKind::Detail,
            Self::ContactList => ScreenKind::List,
            Self::ContactDetail => ScreenKind::Detail,
            Self::ContactEdit => ScreenKind::Form,
            Self::Settings => ScreenKind::Settings,
            Self::TagManagement => ScreenKind::List,
            Self::Logs => ScreenKind::List,
            Self::AppleConflict => ScreenKind::Detail,
            Self::SyncConflictGroup => ScreenKind::Detail,
        }
    }
}
