//! Generated by `scripts/gen_r14.py`. Do not edit.
//! ADR 0004 R11 token tables. Light hex plus sourced dark companions.

pub mod gallery {
    pub const ACCENT: &str = "#C48A3E";
    pub const ACCENT_DARK: &str = "#D4994D";
    pub const BG: &str = "#FAF7F2";
    pub const BG_CARD: &str = "#FFFFFF";
    pub const BG_GROUPED: &str = "#F2EDE5";
    pub const INK: &str = "#1C1A16";
    pub const INK2: &str = "#5E574D";
    pub const INK3: &str = "#958D82";
    pub const DESTRUCTIVE: &str = "#B24A3A";
    pub const SEPARATOR_INK: &str = "#3C372D";
    pub const CARD_RADIUS: f64 = 14.0;
    pub const MEMORY_RADIUS: f64 = 20.0;
    pub const SEPARATOR_OPACITY: f64 = 0.1;
    pub const ACCENT_SOFT_OPACITY: f64 = 0.13;
}

pub mod contacts {
    pub const ACCENT: &str = "#336BC7";
    pub const ACCENT_DARK: &str = "#4D85DE";
    pub const CARD_RADIUS: f64 = 12.0;
}

pub mod music {
    pub const ACCENT: &str = "#C0392B";
    pub const ACCENT_DARK: &str = "#D14738";
    pub const CARD_RADIUS: f64 = 12.0;
}

pub mod health {
    pub const CARD_RADIUS: f64 = 12.0;
}
