//! Generated by `scripts/gen_r14.py`. Do not edit.
//! ADR 0004 R11 token tables. Hex strings; no UI toolkit.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ColorHex {
    pub light: &'static str,
    pub dark: Option<&'static str>,
}

pub mod gallery {
    use super::ColorHex;
    pub const ACCENT: ColorHex = ColorHex {
        light: "#C48A3E",
        dark: Some("#D4994D"),
    };
    pub const BG: ColorHex = ColorHex {
        light: "#FAF7F2",
        dark: None,
    };
    pub const BG_CARD: ColorHex = ColorHex {
        light: "#FFFFFF",
        dark: None,
    };
    pub const BG_GROUPED: ColorHex = ColorHex {
        light: "#F2EDE5",
        dark: None,
    };
    pub const INK: ColorHex = ColorHex {
        light: "#1C1A16",
        dark: None,
    };
    pub const INK2: ColorHex = ColorHex {
        light: "#5E574D",
        dark: None,
    };
    pub const INK3: ColorHex = ColorHex {
        light: "#958D82",
        dark: None,
    };
    pub const DESTRUCTIVE: ColorHex = ColorHex {
        light: "#B24A3A",
        dark: None,
    };
    pub const SEPARATOR_INK: ColorHex = ColorHex {
        light: "#3C372D",
        dark: None,
    };
    pub const CARD_RADIUS: f64 = 14.0;
    pub const MEMORY_RADIUS: f64 = 20.0;
    pub const SEPARATOR_OPACITY: f64 = 0.1;
    pub const ACCENT_SOFT_OPACITY: f64 = 0.13;
}

pub mod contacts {
    use super::ColorHex;
    pub const ACCENT: ColorHex = ColorHex {
        light: "#336BC7",
        dark: Some("#4D85DE"),
    };
    pub const CARD_RADIUS: f64 = 12.0;
}

pub mod music {
    use super::ColorHex;
    pub const ACCENT: ColorHex = ColorHex {
        light: "#C0392B",
        dark: Some("#D14738"),
    };
    pub const CARD_RADIUS: f64 = 12.0;
}

pub mod health {
    pub const CARD_RADIUS: f64 = 12.0;
}
